# Gives the clientset in main.go the authorization to create a new pod
# note one needs to run kubectl apply -f kubeclient-rbac.yaml in order for this file to take effect
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: go-tutorials-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: go-tutorials-service-account
  namespace: default