# yaml so that skaffold can be used to build and push the code
apiVersion: skaffold/v2beta5
kind: Config
metadata:
  name: skaffold
build:
  artifacts:
  - image: skaffold-example
deploy:
  kubectl:
    manifests:
    - k8s-pod.yaml
